### PR TITLE
Re-fix isObservable() and add test - fixes #29

### LINKED ISSUE #29: 0.6.0 broke default rendering
Hey @SamVerschueren, I am glad for the new renderers!

But I just experienced an issue when trying to use 0.6.0 for npm-launch. Seems like it doesn't render much anymore when using the default renderer. Maybe it's rendering the listr instance as `completed` before it actually is?

listr-0 5 0

listr-0 6 0

### PR DESCRIPTION
**Pull request by andywer**
Moved `isListr` and `isObservable` into a separate `util.js` and added a unit test for the `util.js`. Verifies that `isObservable()` works with both `rxjs/Observable` and `zen-observable`.

`isObservable()` checks for `obj.constructor.name === 'Observable'` now. Still somewhat hacky, but at least a plausible way to go as long as there's no official solution.

Btw: Maybe propose this to sindresorhus/is-observable#1?

### CODE REVIEW

File: test/util.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import test from 'ava';
+import {Observable as RxObservable} from 'rxjs/Observable';
+import ZenObservable from 'zen-observable';
+import Listr from '../';
+import {isListr, isObservable} from '../lib/util';
+
+test('isListr', t => {
+	t.falsy(isListr(null));
```
Comment (SamVerschueren) [inline test/util.js]: Use `t.false` and `t.true`.

File: lib/util.js [hunk 2]
```diff
@@ -0,0 +1,8 @@
+'use strict';
+
+const isListr = obj => obj && obj.setRenderer && obj.add && obj.run;
```
Comment (SamVerschueren) [inline lib/util.js]: Export the function right away without intermediate step.

File: test/util.js (hunk 1 above)
Comment (andywer) [inline test/util.js]: Initially I did. But it failed, since right now `isListr()` will return `null` or the listr instance itself if it is. So then I just added a `... ? true : false` to `isListr()`, but `xo` failed, because for some weird reason it complains that the ternary is superfluous...

Any suggestions?

Comment (SamVerschueren) [inline test/util.js]: Wrap it in `Boolean(...)`

**Comment by andywer** [comment]
Fixed the code 👍

**Comment by SamVerschueren** [comment]
Can you rename `util` to `utils`? Filenames and variables.

**Comment by SamVerschueren** [comment]
Sweet! Thanks for looking into this @andywer :beers: !

**Comment by andywer** [comment]
@SamVerschueren No problem 🙌

**Comment by TylorS** [comment]
This actually breaks the stuff that I'm working on because of the changes to `isObservable`. The stream library I'm using is [most.js](https://github.com/cujojs/most) and it's `constructor.name` is `Stream` and not Observable. However it *does* implement Observable interfaces.

**Comment by SamVerschueren** [comment]
@TylorS I'm not interested to actually support all the possible observable-like implementations out there. The reason I use duck-typing currently is because of an issue with [is-observable](https://github.com/sindresorhus/is-observable/issues/1) which uses `Symbol` to detect if it is an Observable. If that issue gets fixed someday, I will start using that one and `most.js` will break again. So currently I'm trying my best to support `RxJs` and `zen-observable`. The only thing I can say about your issue is that maybe you can wrap it in a real Observable?

**Comment by andywer** [comment]
@TylorS @SamVerschueren I can understand both your standpoints. I had a quick look and `is-observable` would indeed work with `most.js`.

So how about that: We check with the current custom logic and fallback to `is-observable` or vice versa. If one of both is true we can be almost certain it is an Observable.

PS: I can also open an issue on `zen-observable` to use the `symbol-observable` so `is-observable` will work with the `zen-observable` as well.

**Comment by SamVerschueren** [comment]
Let's discuss this further in #31
