### PR TITLE
fix(task): update isObervable check

### LINKED ISSUE #27: The observable interface no longer contains the forEach method
The Observable interface as defined [here](https://github.com/tc39/proposal-observable#observable)
No longer contains the method `forEach()` which is used to determine if an object returned by a task is an observable [here](https://github.com/SamVerschueren/listr/blob/master/lib/task.js#L21).

I'd propose adjusting that line to something like
```js
const isObservable = obj => obj && typeof obj.subscribe === 'function' && typeof obj.constructor.from === 'function'
```

I don't forsee the `from()` static method being removed since it's the basis for converting to and from different observable types. 

I'd be happy to PR this if it would be accepted. 

Thank you for you time :smile:

### PR DESCRIPTION
**Pull request by TylorS**
Updates the `isObservable` check in `lib/task.js` to be more reliable and up to date with the evolving ES Observable specification. 

Closes #27

### CODE REVIEW

File: lib/task.js [hunk 1]
```diff
@@ -18,7 +18,8 @@ const skipped = chalk[color](figures.arrowDown);
 
 const isListr = obj => obj && obj.setRenderer && obj.add && obj.run;
 // https://github.com/sindresorhus/is-observable/issues/1
-const isObservable = obj => obj && obj.subscribe && obj.forEach;
+const isObservable = obj => obj && typeof obj.subscribe === 'function' &&
+  typeof obj.constructor.from === 'function';
```
Comment (SamVerschueren) [inline lib/task.js]: Write it on one line

**Comment by TylorS** [comment]
Updated

**Comment by SamVerschueren** [comment]
Thanks @TylorS !
